package swa.tools.java.doc.generator.test;

import java.util.List;

public class CreditBankinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_bankinfo
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_bankinfo
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_bankinfo
     */
    protected List<CreditBankinfoExample> oredCriteria;

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public List<CreditBankinfoExample> getOredCriteria() {
        return oredCriteria;
    }

    public void setOredCriteria(List<CreditBankinfoExample> oredCriteria) {
        this.oredCriteria = oredCriteria;
    }
}