package swa.tools.java.doc.generator.test;

public interface CreditBankinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_bankinfo
     *
     * @mbggenerated
     */
    Integer countByExample(CreditBankinfoExample example);

}